#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker5"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "8f71e52e3af646308e86d093d5c8bdb3" }
]

[assets]
directory = "./public"
